### ISSUE TITLE
your NN's : difference ?

### ISSUE THREAD

**Issue by tissatussa** [zzzzz151/z5#4]
i see many other NNUE files in your package .. can they be used instead of the default one ? What's their difference ? Could we train with specific pawn structures / opening setups ?

https://github.com/zzzzz151/z5/assets/1109281/228b60f4-ed35-462d-ba70-8a3fd08f250d

**Comment by zzzzz151** [comment]
Those are NNs I've trained and tested.
You can change to a .nnue NN by adapting the NET_FILE and HIDDEN_LAYER_SIZE constants in nnue.hpp.
For net_512_1B_25wdl.nnue, you'll also need to change outputWeights to int16_t.
